FROM quay.io/jupyter/base-notebook:python-3.13

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
USER jovyan
